# Generated by Django 5.2.5 on 2025-08-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='surname',
            field=models.CharField(default='Georgiev', max_length=100),
            preserve_default=False,
        ),
    ]
